name: CI-build

on:
  push:
    branches:
      - release

jobs:
  test_and_build:
    runs-on: ubuntu-20.04
    env:
      REGISTRY: gushcloud/
      CONTAINER_NAME: postgresql-client

    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1

     - name: Login to Dockerhub Container Registry
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.OS_DOCKER_USER }}
         password: ${{ secrets.OS_DOCKER_SECRET }}

     - name: version
       run: "echo GITHUB run id: $GITHUB_RUN_NUMBER"

     - name: Build container image
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: .
         builder: ${{ steps.buildx.outputs.name }}
         tags: |
           ${{ env.REGISTRY }}${{ env.CONTAINER_NAME }}:latest
           ${{ env.REGISTRY }}${{ env.CONTAINER_NAME }}:${{ github.run_number }}
         file: Dockerfile
         push: true

     - name: Image digest
       run: echo ${{ steps.docker_build.outputs.digest }}
